# Funding options for MEGAGENT

# GitHub Sponsors
github: [ELMOURABEA]

# Ko-fi
ko_fi: elmourabea

# Custom sponsorship URLs
custom: 
  - "https://ko-fi.com/elmourabea?ref=onboarding_email_founderwelcome"
  - "https://github.com/sponsors/ELMOURABEA"
github: [ELMOURABEA,MeGaOcToOoN]
patreon: ELMOURABEA
tidelift: npm/ELMOURABEA-package
custom: [MeGaOcTo@elmorab3.com]
